### ISSUE TITLE
Index.js question

### ISSUE THREAD

**Issue by SrKirush** [Walkoud/raidbotdiscord#13]
What does index.js do, and means? I just see a bunch of numbers, and I dont know what it is, Sorry for my ignorance

**Comment by johan-perso** [comment]
It's because the stupid creator hide the code for we don't see that there is a virus hidden in the code

**Comment by Walkoud** [comment]
Lol, i can't create virus with a javascript file, I just obfuscated the code so that it wouldn't be stolen from me, I never said it was open source.

**Comment by TKperson** [comment]
why do you even publish the source code when it can be decoded....
This is just dumb, just compile JavaScript to an exe file if you don't want people to see it....

**Comment by Walkoud** [comment]
> why do you even publish the obfuscated source code on github when you know it can be deobfuscated....
> This is just dumb, just compile JavaScript to an exe file if you don't want people to see it.... 

Most people cannot obfuscate the code.  If the person knows how to deobfucate the code, then he already knows how to code this kind of bot.  Do you understand my logic?
