### ISSUE TITLE
index.js 3.1a

### ISSUE THREAD

**Issue by sadrekha** [Walkoud/raidbotdiscord#17]
Where are the webhooks of the old index.js? 😃

**Comment by Walkoud** [comment]
Oh, Were there webhooks before?

**Comment by sadrekha** [comment]
Baaah ouais mon gars 😃

**Comment by Walkoud** [comment]
Ouai gros, je vais le remettre désolé

**Comment by Walkoud** [comment]
Voilà c'est bon, tu peux mettre à jour, si y'a un bug n'hésite pas à créer un autre, ou me contacter sur discord Walkoud#1981
