### ISSUE TITLE
Obfuscated

### ISSUE THREAD

**Issue by littlepig453** [Walkoud/raidbotdiscord#18]
My computer can't run it because of the o fuscated code. Do you have an unobfuscated version?

**Comment by Walkoud** [comment]
> My computer can't run it because of the o fuscated code. Do you have an unobfuscated version?

Your computer can run the code even if it's obfuscated

**Comment by r3ngan** [comment]
hi, if you think there is a token grabber, know that there isn't **(I deobfuscated the code but I don't share it out of respect to the creator)**, obfuscer codes still work, just enter everything you need in the configs and npm i

**Comment by Olyno** [comment]
```js
let total = 0;
for (let i = 0; i < 10; i++) {
  total += i;
}
console.log("Total: " + total);
```

This is the deobfuscated code. This is stupid to make a project open source to obfuscate it, even more for that code. Just make it private in that case, or simply delete your file if not used (which looks like it is).

**Comment by Walkoud** [comment]
> ```js
> let total = 0;
> for (let i = 0; i < 10; i++) {
>   total += i;
> }
> console.log("Total: " + total);
> ```
> 
> This is the deobfuscated code. This is stupid to make a project open source to obfuscate it, even more for that code. Just make it private in that case, or simply delete your file if not used (which looks like it is).

Bro, I wanted to share it only for my discord server. Why do you come and bother me "gneugneu this is so stupid", I don't give a fuck about what you say.

**Comment by littlepig453** [comment]
If you want to share it then share it on your discord server, dont obfuscate things on a platform mostly based for open source projects.

**Comment by Walkoud** [comment]
> If you want to share it then share it on your discord server, dont obfuscate things on a platform mostly based for open source projects.

![het.gif](https://user-images.githubusercontent.com/38588921/167223337-22ae5c2c-4868-4a56-96d7-52a06a7301a3.gif)
