### ISSUE TITLE
Why is it obfuscated, and is it a token logger ? (i found a webhook string, but there's no webhook link)

### ISSUE THREAD

**Issue by XxDarknedxX** [Walkoud/raidbotdiscord#19]
yo, while i just run, i realized its obfuscated later like around 8 hours after running it, and i panicked after realizing its obfuscated so bad with uft- strings and stuff, so i had to deobfuscate it because i can't trust a random source, and while i was deobfuscating it i found something so interesting, yep there's no webhook link but still since i couldn't manage to deobfuscate it 100%, can you made a explanation for this ?
![image](https://user-images.githubusercontent.com/95621387/165063859-090564ab-2424-484f-9484-884bf2372ea6.png)
Edit 1 : I tried to use http debugger on it and i didn't find any webhook, but still, i want a explanation for why it's not open source ?

**Comment by Walkoud** [comment]
The bot spams the channels in webhook, it allows to raid a server without revealing the author of the raid

**Comment by Walkoud** [comment]
![image](https://user-images.githubusercontent.com/38588921/165084488-1bea985a-f5fa-4f14-8651-066385cd476a.png)

**Comment by XxDarknedxX** [comment]
> The bot spams the channels with webhook, it allows to raid a server without revealing the author of the raid

Ah sorry, for assuming you, but the obfuscated source has a little scared me tbh

**Comment by NotFubukIl** [comment]
There is a webhook, but no token logger

**Comment by Yan-Jobs** [comment]
But why is it obfuscated tho, open source should not be obfuscated

**Comment by Walkoud** [comment]
> But why is it obfuscated tho, open source should not be obfuscated 

This is not open source

**Comment by Yan-Jobs** [comment]
> > But why is it obfuscated tho, open source should not be obfuscated
> 
> This is not open source

So why on GitHub, you just have to use discord’s CDN.

**Comment by Walkoud** [comment]
> > > But why is it obfuscated tho, open source should not be obfuscated
> > 
> > 
> > This is not open source
> 
> So why on GitHub, you just have to use discord’s CDN.

I share via github and it's my choice, what's the problem

**Comment by iloveyumyumshrimpnoodles** [comment]
> > > > But why is it obfuscated tho, open source should not be obfuscated
> > > 
> > > 
> > > This is not open source
> > 
> > 
> > So why on GitHub, you just have to use discord’s CDN.
> 
> I share via github and it's my choice, what's the problem

The problem is that github is made for sharing open source code, not obfuscated scripts that are most likely backdoored.

**Comment by Walkoud** [comment]
> > > > > But why is it obfuscated tho, open source should not be obfuscated
> > > > 
> > > > 
> > > > This is not open source
> > > 
> > > 
> > > So why on GitHub, you just have to use discord’s CDN.
> > 
> > I share via github and it's my choice, what's the problem
> 
> The problem is that github is made for sharing open source code, not obfuscated scripts that are most likely backdoored.

I made it to share to my discord server

**Comment by iloveyumyumshrimpnoodles** [comment]
> I made it to share to my discord server
Then why not upload it on anonfiles, MEGA or any other file sharing service?

**Comment by Walkoud** [comment]
> > I made it to share to my discord server
> 
> Then why not upload it on anonfiles, MEGA or any other file sharing service?
> 

I prefer github, it's much more accessible, we have an issue page, a readme page etc.

**Comment by Walkoud** [comment]
> > I made it to share to my discord server
> 
> Then why not upload it on anonfiles, MEGA or any other file sharing service?
> 

I prefer github, it's much more accessible, we have an issue page, a readme page etc.

**Comment by iloveyumyumshrimpnoodles** [comment]
> I prefer github, it's much more accessible, we have an issue page, a readme page etc.

Github isn't made to upload obfuscated content tho

**Comment by Walkoud** [comment]
> > I prefer github, it's much more accessible, we have an issue page, a readme page etc.
> 
> Github isn't made to upload obfuscated content tho
> 

Ok report then, what are you waiting
