### ISSUE TITLE
bug .res/.red

### ISSUE THREAD

**Issue by NathanGinette** [Walkoud/raidbotdiscord#23]
when I do .res or .red the channels are created fine but no message is sent.

When I launch the bot I get this message:
"(node:16712) DeprecationWarning: Guild#me is deprecated. Use Guild#members#me instead. (Use `node --trace-deprecation ...` to show where the warning was created)" 
but it doesn't stop me from running commands.

![image](https://user-images.githubusercontent.com/99477749/221301840-d6276424-6fe6-412c-a259-984905d1bb80.png)

**Comment by Walkoud** [comment]
> when I do .res or .red the channels are created fine but no message is sent.
> 
> When I launch the bot I get this message: "(node:16712) DeprecationWarning: Guild#me is deprecated. Use Guild#members#me instead. (Use `node --trace-deprecation ...` to show where the warning was created)" but it doesn't stop me from running commands.
> 
> ![image](https://user-images.githubusercontent.com/99477749/221301840-d6276424-6fe6-412c-a259-984905d1bb80.png)

I use old Discord.js version, this is normal

**Comment by aikooo7** [comment]
Shouldn't this be closed? @Walkoud

**Comment by Walkoud** [comment]
> Shouldn't this be closed? @Walkoud 

Yes
